# Generated by Django 5.2 on 2025-05-04 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Katalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('rezyseria', models.CharField(max_length=100)),
                ('gatunek', models.CharField(max_length=100)),
                ('ilosc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=20)),
                ('haslo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Wypozyczenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('katalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.katalog')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.uzytkownik')),
            ],
        ),
    ]
