# Generated by Django 5.2 on 2025-05-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_wypozyczenia_uzytkownik'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uzytkownik',
        ),
    ]
